title = "Ethereum Improvement Proposals (Theme Demo)"
description = "Ethereum Improvement Proposal (EIP) demo theme for the Zola static site generator."

# The URL the site will be built for
base_url = "https://eips-wg.github.io/eips-theme"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    { name = "status", feed = true },
    { name = "category", feed = true },
    { name = "type", feed = true },
]

generate_feeds = true

[link_checker]
internal_level = "warn"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "css"

highlight_themes_css = [
    { theme = "base16-ocean-dark", filename = "assets/css/syntax-theme-dark.css" },
    { theme = "base16-ocean-light", filename = "assets/css/syntax-theme-light.css" },
]

[extra.github]
eip_repository = "https://github.com/eips-wg/eips-theme"

[extra.taxonomies.status.stagnant]
tooltip = "This EIP had no activity for at least 6 months. This EIP should not be used."

[extra.taxonomies.status.withdrawn]
tooltip = "This EIP has been withdrawn, and should not be used."

[extra.taxonomies.status.draft]
tooltip = "This EIP is not yet recommended for general use or implementation, as it is subject to normative (breaking) changes."

[extra.taxonomies.status.review]
tooltip = "This EIP is not yet recommended for general use or implementation, as it is subject to normative (breaking) changes."

[extra.taxonomies.status.last-call]
tooltip = "This EIP is in the last call for review stage. The authors wish to finalize the EIP and ask you to provide feedback."

[extra.taxonomies.status.final]
tooltip = "This EIP is completed and no longer expected to change."

[extra.taxonomies.category.erc]
tooltip = "Application-level standards and conventions, including contract standards such as token standards, name registries, URI schemes, library/package formats, and wallet formats."

[extra.taxonomies.category.interface]
tooltip = "Improvements around client API/RPC specifications and standards, and also certain language-level standards like method names and contract ABIs."

[extra.taxonomies.category.networking]
tooltip = "Improvements around devp2p and Light Ethereum Subprotocol, as well as proposed improvements to network protocol specifications of whisper and swarm."

[extra.taxonomies.category.core]
tooltip = "Improvements requiring a consensus fork, as well as changes that are not necessarily consensus critical but may be relevant to “core dev” discussions."

[extra.taxonomies.type.informational]
tooltip = "Describes an Ethereum design issue, or provides general guidelines or information to the Ethereum community, but does not propose a new feature. Informational EIPs do not necessarily represent Ethereum community consensus or a recommendation, so users and implementers are free to ignore Informational EIPs or follow their advice."

[extra.taxonomies.type.meta]
tooltip = "Describes a process surrounding Ethereum or proposes a change to (or an event in) a process."

[extra.taxonomies.type.standards-track]
tooltip = "Describes any change that affects most or all Ethereum implementations or any application."
