name = "eips-theme"
description = "A theme for Ethereum Improvement Proposals"
license = "MIT"
homepage = "https://github.com/eips-wg/eips-theme"
# The minimum version of Zola required
min_version = "0.17.2"
# An optional live demo URL
demo = "https://eips-wg.github.io/eips-theme"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Sam Wilson"
homepage = "https://github.com/SamWilsn"
